

# Added by Toolbox App
export PATH="$PATH:/Users/arnavsharma/Library/Application Support/JetBrains/Toolbox/scripts"


eval "$(/opt/homebrew/bin/brew shellenv)"
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval $(/opt/homebrew/bin/brew shellenv)
eval "$(/opt/homebrew/bin/brew shellenv)"
